### PR TITLE
Made it easier to run local docker container with docker-compose

### PR DESCRIPTION
**Pull request by dbdean**
I was finding some inefficiencies in having to build and run my own local docker instead of using the prebuilt ones, so I set up a single container docker-compose to help out. This PR has the following main changes:

1. docker container now runs as non-priviledged user instead of root (no more root-owned files in your data directory)
2. environment files can be saved in a (gitignored) docker.env file to avoid having to pass many configuration parameters on the command line
3. local docker builds are as easy as `docker-compose build`, `docker-compose run data download-osm-tiles`, `docker-compose run data`.
4. because docker-compose mounts the code into the container as a volume, you can make changes without having to rebuild (unless you need to refresh the node_modules - then you need to rebuild).

I have also updated the README to reflect these changes.

I would appreciate any comments you have and are happy to help improve this PR in any way to help get it in.

### CODE REVIEW

**Comment by drewbo** [comment]
Don't have a ton of time for a full review but on quick scan this looks good. I'll test it out and merge in sometime in the next week. I also love the idea of the `.env` file since it could stand is as "configuration" for multiple dataset preparations. Thanks

**Comment by drewbo** [comment]
Man my "next week" comment looks pretty bad above. Checking this out today and will update. Thanks again @dbdean

**Comment by drewbo** [comment]
Looks to good to merge:
- For my understanding: What's the benefit of change number 1? (Not having root-owned folders in data)
- Also I case you see anything odd: I started to make a `README` change to keep some lines together but then I realized you were being a good gitizen and keeping line lengths trimmed (something I'm terrible at) so I reset and force pushed over my own change

**Comment by dbdean** [comment]
@drewbo, the not having root-owned folders in data means that you don't have to use `sudo` to access or modify the data when you are not inside of docker, and it also (more importantly) is a side-effect of no longer running the docker container as a privileged user when it is not required to be so, which is generally a good security principle.

**Comment by dbdean** [comment]
Thanks @drewbo!

**Pull request merged**
